# Generated by Django 5.2 on 2025-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form133',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_nr', models.CharField(max_length=5)),
                ('incident_naam', models.CharField(max_length=30)),
                ('datum', models.DateField()),
                ('locatie', models.CharField(max_length=100)),
            ],
        ),
    ]
