# Generated by Django 5.2 on 2025-05-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form133next',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_nr', models.CharField(max_length=5)),
                ('tijd', models.CharField(max_length=30)),
                ('team', models.DateField()),
                ('bericht', models.CharField(max_length=100)),
            ],
        ),
    ]
