# Generated by Django 5.2 on 2025-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form133next',
            name='incident_naam',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
