# Generated by Django 5.2 on 2025-05-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0002_form133next_incident_naam'),
    ]

    operations = [
        migrations.AddField(
            model_name='form133next',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form133next',
            name='locatie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
