# Generated by Django 5.2 on 2025-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0003_form133next_datum_form133next_locatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form133',
            name='incident_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
