# Generated by Django 5.2.1 on 2025-05-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0004_alter_form133_incident_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form133next',
            name='incident_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
