# Generated by Django 5.2.1 on 2025-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0005_alter_form133next_incident_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form133next',
            name='tijd',
            field=models.TimeField(),
        ),
    ]
