# Generated by Django 5.2 on 2025-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0005_alter_form133next_incident_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form133next',
            name='team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form133next',
            name='tijd',
            field=models.CharField(max_length=10),
        ),
    ]
