# Generated by Django 5.2 on 2025-05-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0006_alter_form133next_team_alter_form133next_tijd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form133next',
            name='tijd',
            field=models.TimeField(),
        ),
    ]
